export const API_ENDPOINTS = {
    PROFILE: "user-profile/",
    LOGIN: "seller/login/",
    DASHBOARD_CARD: "common/customer-list/",
    CUSTOMER: "common/customer-list/",
    CUSTOMER_DETAILS: "common/customer-detail",
    CUSTOMER_STATUS_COUNT: "common/customer-status-count/",
    SECTOR_LIST: "common/sectors-list/",
    SECTOR_MEDICAL: "common/medical-sector-list",
    LOCATION: "common/location-list/",
    CUSTOMER_SOURSE: "common/customer-source/",
    PRODUCTS: "common/product-list/",
    PAYMENT_TYPES: "common/payment-types/",
    PAYMENT_METHODS: "common/payment-methods/",
    SELLER: "seller-list/",
    CREATE_SELLER: "seller/register/",
    PAGE: "page-list/",
    SELLER_DETAILS: "seller-details",
    SELLER_UPDATE: "seller/update",
    SELLER_CUSTOMERS: "common/seller/customers/",
    SELLER_REQUEST_UPDATE: "common/change-request-status-update",
    SELLER_REQUESTS_LIST: "common/change-request-list/",
    NOTIFICATION_LIST: "notifications-list/",
    COMMENT_LIST: "common/comment-list/",
    COMMENT_DELETE: "common/comment-delete/",
    CREATE_COMMENT: "comments/create",
    USER_SEARCH: "user-search/",
    ADMIN_DASHBOARD: "common/admin-dashboard-counts/",
    SELLER_DASHBOARD: "seller-dashboard/customer/",
    SELLER_STATSTIC: "profile-dashboard/",
    SELLER_CUSTOMER_VIEW: "seller-customer-view/",
    SELLER_CALENDAR_CLOSE: "seller/clendar-close-date/",
    SELLER_CALENDAR_LIST: "seller/calendar-list/",
    CALENDAR_IS_AVAILABLE: "calendar-is_available/",
    CUSTOMER_DETAILS_SELLERS: "customer-in-seller/"


}
